require("indent_blankline").setup({
  show_trailing_blankline_indent = false,
  use_treesitter = false,
  char = "▏",
  enabled = true,
  filetype_exclude = {
    "dashboard",
    "help",
    "toggleterm",
    "packer",
    "aerial",
    "alpha",
    "man",
    "TelescopePrompt",
    "TelescopeResults",
    "NeogitCommitView",
    "dockerfile",
    "NvimTree",
    "NeovitStatus",
    "tsplayground",
    "startup",
    "dap-repl",
  },
  max_indent_increase = 10,
})
