require("project_nvim").setup({
  manual_mode = false,
  detection_methods = { "pattern" },
  scope_chdir = 'tab',
  patterns = {
    "_darcs",
    ".project",
    ".bzr",
    ".git",
    ".hg",
    ".svn",
    "go.mod",
    "package.json",
    "Pipfile",
    "poetry.lock",
    "pyrightconfig.json",
    "pyproject.toml",
    "setup.cfg",
    "setup.py",
  },
  ignore_lsp = { "null-ls" },
  silent_chdir = true,
})
